### PR TITLE
pico-display: Expose RGB332 support

### PR DESCRIPTION
**Pull request by kennylevinsen**
It's unclear why this was not enabled.

### CODE REVIEW

**Comment by notro** [comment]
RGB332 is not supported by the ST7789 controller, it only supports RGB565 and RGB666, that's why it's not enabled.

The reason for the other formats in this file is that I use this display to test the formats that are not supported by the Linux gadget. There is code that converts these formats to RGB565 which is what the controller is set up for.

So I'll drop this one.

I don't know how much use this project sees, I just wanted to do an microcontroller implementation that people could copy from to use on their favourite microcontroller. The reason I picked the Pico is that I knew it would be around for a long time at an affordable price.

How do you use this project?

**Comment by kennylevinsen** [comment]
My primary use-case for gud-pico so far has been to work on support for render-less KMS nodes and reduced bitdepth support in wlroots[^1], where a tiny and cheap display[^2] has been convenient for backpack reasons while simultaneously avoiding the horrors of a certain proprietary USB display solution. Seeing that the conversion code was there, I didn't see the harm in exposing the option - even if the display doesn't natively support it, with just USB1.1 the pico and pico2 can use all the bandwidth help they can get. :/

While it wouldn't be the ST7789-supporting gud-pico as-is, I was planning on attempting a practical e-paper based auxiliary info display based on this. `DRM_FORMAT_C1` should help with the USB1.1 bottleneck, and sorting out a way to actually support such an exotic format without hacks might be a "fun" challenge on the wlroots side of things. :)

Should such a thing materialize, it would be up to you to decide if you think expanding gud-pico is in scope or if you'd rather keep it as a ST7789 demo/reference.

[^1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4824
[^2]: https://shop.pimoroni.com/products/pico-display-pack-2-8

**Comment by notro** [comment]
> I didn't see the harm in exposing the option - even if the display doesn't natively support it, with just USB1.1 the pico and pico2 can use all the bandwidth help they can get. :/

The problem is that the host driver will add XRGB8888 emulation for the first supported format: RGB565 and AFAIK most/all? modern userspace will pick XRGB8888. X will pick RGB565 because it supports DRM_CAP_DUMB_PREFERRED_DEPTH ([gud ref](https://elixir.bootlin.com/linux/v6.11.1/source/drivers/gpu/drm/gud/gud_drv.c#L552-L554)).
So is there any userspace that will/can pick RGB332?

> I was planning on attempting a practical e-paper based auxiliary info display based on this.

I'm happy to take patches for that, I had for some time an ambition to add support for a Pimoroni e-paper display with an onboard RP2040, as a non MIPI DCS/DBI example, but never came around to doing that.

Oh so you're working on wlroots. I wish I knew more about the userspace side of graphics, I've only worked in the kernel.  One big downside of GUD is the lack of video compression support. It works fine for office desktop use, but not so fine for moving pictures. I've been thinking about how to add support for that, but I'm not sure if it's actually doable. Displaylink uses the GPU for video encoding, but AFAIU they have most of the display driver running in userspace so they can use the GPU. Doing it from the kernel is a different can of worms. I have taking a quick look at a VP9 software encoder, but I'm not capable of pulling the right bits into the kernel, and I'm afraid it will be a lot of code even if it was doable. So GUD will stay a niche thing I guess as long as there is no video compression.

**Comment by kennylevinsen** [comment]
> So is there any userspace that will/can pick RGB332?

In my MR, we are not forcing dumb buffers, but rather use whatever the current renderer is providing - dma-bufs in the general case. As such, we are not supposed to read `DRM_CAP_DUMB_PREFERRED_DEPTH` according to the current uAPI.

Instead, the render format is subject to compositor decision. In case of sway, this [defaults to a search through supported formats](https://github.com/swaywm/sway/blob/c90cb37b2a0861548461daa9b75d75317e01b679/sway/config/output.c#L788) (an intersection between the renderer's supported formats and the KMS plane's supported formats), with a [command for manual overrides](https://github.com/swaywm/sway/blob/master/sway/commands/output/render_bit_depth.c).

I haven't added RGB332 to the list yet because my GPU doesn't support it as a render format, and the multi-GPU path in wlroots does not currently have a way to degrade to CPU rendering for format conversions. It was originally designed for cases where you have multiple full-fat GPUs, relying on the auxillary GPU's own render node to import and blit the main GPU's render buffer onto something that can be scanned out.

One can switch entirely to the pixman software renderer to sidestep the hardware support/mgpu smarts issue, and then it's probably just a matter of adding RGB332 to [the pixman pixel format list](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/render/pixman/pixel_format.c?ref_type=heads).

> I wish I knew more about the userspace side of graphics

One big benefit of Wayland is that it's a lot more self-contained for experimentation, and the display-side is fairly easy to deal with. Rendering is a bit hairier, in particular if you need to dive into user-space driver code.

> One big downside of GUD is the lack of video compression support.

Yeah, That Other USB Solution is quite a hack. You submit your FB to KMS, which is then fed back by the `evdi` module to user-space where their daemon imports it back to the same render node you just rendered it on, where it performs some video compression and secret sauce encryption...

One random and not at all thought through thought I had would be a new format (`DRM_FORMAT_COMPRESSED_XYZ`) and a way for mesa to do such encoding, instead of trying to hide the encoding entirely. Another - and probably much easier - approach could be to sidestep KMS entirely, and have a `libgud` wlroots backend that opened the USB device directly and did whatever encoding was necessary, at the cost of being less plug-and-play. That would also allow a less dumb implementation for That Other Solution.

Not sure if we have already reached the limit for lossless compression, but tbh a lot of the bandwidth issues would go away if microcontrollers gained USB2.0 PHY's, and Pi's 3.0 PHY's.

**Comment by notro** [comment]
> RGB332

320x240 RGB565 is [slow](https://github.com/notro/gud/wiki/Performance#measure-throughput-using-perf-directpy-and-perf-kmspy) over USB1.1 but it is possible to use a Pi Zero with such a display panel. I hacked together a generic [MIPI DBI driver](https://github.com/notro/gud/wiki/MIPI-DBI-SPI-driver) for this (does not support x/y offsets) available in the [Pi image](https://github.com/notro/gud/releases). But it's only tested on one panel so it might have bugs. This is the big downside of a one maintainer hobby project like this, things doesn't see much testing. 

> DRM_FORMAT_COMPRESSED_XYZ

[Format modifiers](https://docs.kernel.org/userspace-api/dma-buf-alloc-exchange.html#formats-and-modifiers) are used to describe things like compression, but they are vendor specific so I don't know if it is possible to use a compression modifier for GUD.

I could ofc use the evdi approach and let userspace do the encoding, but I'm not sure if that will be an accepted solution. It's also possible to have an out-of-tree version of gud that does this if mainline won't accept it but that's ofc a maintenance burden.

Since you work on wlroots maybe you know how say a window showing a youtube video is ending up on a hardware plane in KMS. How does the stack pick a plane if more than one is available?

But in order to support video encoding I have to rewrite the gadget side to run in userspace in order to do the decoding. Fortunately this is possible now that USB FunctionFS supports dmabuf (zerocopy). I've started to work on this but I haven't got much time for this hobby nowadays so it's real slow (haven't worked on it for 4 weeks now...).

> but tbh a lot of the bandwidth issues would go away if microcontrollers gained USB2.0 PHY's, and Pi's 3.0 PHY's

USB3.0 would help for Full HD but then 4K comes along...

Rock Pi 4 is the only affordable board ($50-60) I've found that supports 3.0 on the device controller.

**Comment by kennylevinsen** [comment]
> [Format modifiers](https://docs.kernel.org/userspace-api/dma-buf-alloc-exchange.html#formats-and-modifiers) are used to describe things like compression, but they are vendor specific so I don't know if it is possible to use a compression modifier for GUD.

I think the tricky bit would be dealing with the FB being attached in an atomic commit not being a standalone representation of the screen, but just a bitstream segment out of a video stream dependent on previously attached FBs.

The evdi route *would work*, but if the whole thing is handled in user-space, why go through KMS at all? Display servers could have a `libudisplay` based output backend for both gud and DisplayLink.

(Session/VT management would be a bit borked as logind/seatd cannot revoke display access by revoking the drm master role, so that's at least one reason.)

> Since you work on wlroots maybe you know how say a window showing a youtube video is ending up on a hardware plane in KMS. How does the stack pick a plane if more than one is available?

It depends, and not all display servers manage to do this. weston has its own handling of this, while in wlroots it's offloaded to [libliftoff](https://gitlab.freedesktop.org/emersion/libliftoff).

The gist of it is that the display server goes through the stack of surfaces it needs to present from top to bottom. If a surface is opaque, unobstructed, and has a buffer compatible with an unused plane, an atomic test commit is used to test the combination. If it succeeds, we move on to the next surface in the stack, if it fails, that surface and everything below it is composited. Details such as rate of update or previous plane matches might be used as input.

To enable such plane offload in a browser, the browser would use a separate subsurface for the actual video content, attaching the decoded video frames directly to that instead of compositing them onto its main surface on its own.

Desktop GPUs are fairly limited in their planes, often only have one overlay plane (either globally or per CRTC), so other display servers could have more specific heuristics. Cursor planes are always given special treatment.

**Comment by notro** [comment]
Thanks this was really useful info you gave me :tada:

**Pull request closed without merging**
